[ansible]
image=alpine/ansible:2.17.0
additional_packages="openssh sshpass ansible rsync py3-passlib nano"
pull=true
replace=true
exported_bins="/usr/bin/ansible"
exported_bins="/usr/bin/ansible-playbook"
exported_bins="/usr/bin/ansible-vault"
